### ISSUE TITLE
config flag without specifying config name does not work 

### ISSUE THREAD

**Issue by ezekielchentnik** [cognitom/felt#13]
works:
```$ felt --config felt.config.js```

does not work:
```$ felt --config```

documentation makes it sound like the second should work.  might be confusing for folks.

**Comment by cognitom** [comment]
It's a bug. Will fix it soon. Thank you for reporting!

**Comment by cognitom** [comment]
This issue was solved in v0.2.6
https://www.npmjs.com/package/felt
