### ISSUE TITLE
felt-recipe-preact

### ISSUE THREAD

**Issue by ezekielchentnik** [cognitom/felt#14]
I've created a recipe for Preact.  Will create an example for it and try out on a new project

https://www.npmjs.com/package/felt-recipe-preact

@cognitom thoughts on adding an examples section to readme?  Any thoughts on this contribution?

Cheers,
//Zeek

**Comment by cognitom** [comment]
@ezekielchentnik cool! Thanks!
Could you pls add it to [here](https://github.com/cognitom/felt#recipes)?

*Examples* section also sounds nice 👍

**Comment by cognitom** [comment]
PR was merged.
