### ISSUE TITLE
cannot set a dest directory for watching server

### ISSUE THREAD

**Issue by cmnstmntmn** [cognitom/felt#16]
i have the following configs

**server.js**
```js
const
  express = require('express'),
  felt = require('felt')
  config = require('./felt.config.js')

const app = express()

app.use(felt(config))
app.use(express.static('public'))
app.listen(3000)
```

**felt.config.json**
```js
'use strict'

/**
 * Minimal recipe for Felt
 */

const
  rollup = require('felt-rollup'),
  buble = require('rollup-plugin-buble'),
  resolve = require('rollup-plugin-node-resolve'),
  commonjs = require('rollup-plugin-commonjs'),
  postcss = require('felt-postcss'),
  postcssImport = require('postcss-import'),
  cssnext = require('postcss-cssnext'),
  cssnano = require('cssnano')

module.exports = {
  src: 'src',
  export: 'public', // works only from cli (as the docs specify)
  watch: true,
  debug: true,
  patterns: ['entry.js', 'app.css'],
  excludes: ['components/*.js'],	
  // default handlers for each extension
  handlers: {
    '.js': rollup({
      plugins: [
        resolve({ jsnext: true,  main: true, browser: true }),
        commonjs(),
        buble()
      ],
      sourceMap: true
    }),
    '.css': postcss({
      plugins: [
        postcssImport(),
        cssnext({warnForDuplicates: false}),
		cssnano(),        
      ],
      options: {
        map: { inline: false }
      }
    })
  }
}
```

running `node server.js` ignores the `export` param
so, in order to have `<script src="build/entry.js">`

i had to set

``` js
cache: './public/build'
```

all good so far, but `watch: true` is not listening for changes.
any ideea ?

**Comment by cognitom** [comment]
Hi @cmnstmntmn, have you tried serving directly from `src` dir? Felt is designed to compile the file *on-the-fly*.

```javascript
app.use(felt(config))
app.use(express.static('src')) // instead of `public`
```

**Comment by cmnstmntmn** [comment]
can't work, because that's the directory tree

```
public
	build
		app.css
		app.css.map
		app.js
		app.js.map
	index.html
src
	components
	styles
	app.css
	app.js

felt.config.js
server.js
```

**Comment by cognitom** [comment]
Why not put your `index.html` into `src` dir?

**Comment by cmnstmntmn** [comment]
it's a standard php/laravel structure;

```
public
	index.php
	assets/
resources
	css/
	js/
```
pretty messy.
even so i figure how to serve php via express with [php-express](https://github.com/fnobi/php-express) but the page doesn't get refreshed

do i get it wrong, or watching reffers **only** to files changes/recompiling **and it doesn't** include page auto reload ?!

**Comment by cognitom** [comment]
Oh.. can I divide into two question?

### Q1: it's a standard php/laravel structure

We don't have to stick to `src` directory. This could be also fine:

```javascript
// server.js
const app = express()
app.use(felt(config))
app.use(express.static('public')) // serves from 'public'
app.listen(3000)
```

```javascript
// felt.config.js
module.exports = {
  src: 'public', // serves from 'public'
  watch: true,
  handlers: {
    '.js': rollup(...),
    '.css': postcss(...)
  }
}
```

But, if your site is mainly served by PHP, using Felt as a server seems not a good option. My recommended way is exporting it from Felt CLI. Only if your site is 1) running on Express, or 2) Single Page Application, Felt could be the best server solution, I think.

BTW, I didn't know about `php-express`. I think we can make the plugin to handle `.php` file in Felt with `php-express`. Sounds interesting?

### Q2: watching refers only to files changes/recompiling ?

Yes. Felt doesn't do live-reload by itself, because it needs JavaScript injection into the page. If you'd like to live-reload while development, you can use Browsersync or anything with Felt. For example `package.json` could be like this:

```json
{
  "scripts": {
    "server": "felt --src public --watch",
    "watch": "browser-sync start --proxy 'localhost:3000' --files 'cache/**'"
  }
}
```

**Comment by cmnstmntmn** [comment]
i don't know what to say about investing time in php file handling.
since we're going to use browser-sync or another live server anyway; 
we can make use of it's proxy option.
i found [light-server](https://github.com/txchen/light-server), i think is't a good alternative

but still i'm looking for the lightest/fastest possible solution
i'll play with [light-server](https://github.com/txchen/light-server) + [rollup-watch](https://github.com/rollup/rollup-watch) tonight. keep you tuned.

thank you (;

**Comment by cmnstmntmn** [comment]
i'll close this, since it's a way of settings things up more than an issue
